### ISSUE TITLE
Batch Prompt Inputs?

### ISSUE THREAD

**Issue by cyclo-sam** [AndreyGermanov/sam_onnx_full_export#1]
Hello,

Thanks for this repo and the blog post.  

Are you able to run batch prompt inputs with the ONNX model? The original repo's predictor example allows you to do this in PyTorch with the predict_torch() method, but it doesn't cover how to do it in ONNX (one of the many missing components of the ONNX example). I haven't been able to figure this out yet as it seems to only return one mask or multiple with the same prompt.

Can you run batch prompt inference and get a different mask for each individual prompt?

**Comment by AndreyGermanov** [comment]
Hello, 

Not yet, will work on that original repo example next week.

**Comment by moonayyur** [comment]
> Hello,
> 
> Not yet, will work on that original repo example next week.

Hello, any update about this issue ?

**Comment by AndreyGermanov** [comment]
> > Hello,
> > Not yet, will work on that original repo example next week.
> 
> Hello, any update about this issue ?

No, I worked on it, but found that a lot in the core should be rewritten to make it possible and perhaps that these changes will be incompatible with main SAM branch. So, in my opinion, better to ask SAM creators about this: https://github.com/facebookresearch/segment-anything/issues/649
