### ISSUE TITLE
vit_h_encoder is not working

### ISSUE THREAD

**Issue by mayank797** [AndreyGermanov/sam_onnx_full_export#3]
Hello,

Thank you for this repo and the blog post. You did an amazing work.

I found one issue though, when exporting vit_h_encoder it is not merging the bias, weights in the encoder and the encoder size is roughly 1.5MB. I think there needs to be some changes done in order to successfully export it. Could you please help me here?

Thank You!

**Comment by AndreyGermanov** [comment]
Hello,

Yes, this is because the VIT-H model is bigger than 2GB.

If the exported model size is more than 2GB, Pytorch exports it as an ONNX-model with external data, and you need to load it using a different method. See this example in ONNX documentation on how to load ONNX files with external data: https://github.com/onnx/onnx/blob/main/docs/ExternalData.md

**Comment by mayank797** [comment]
Thank you for your quick response.

I tried the steps they told in documentation. Below is the code.

`import onnx
from onnx.external_data_helper import load_external_data_for_model

onnx_model = onnx.load("vit_h_encoder.onnx", load_external_data=False)
load_external_data_for_model(onnx_model, "./output_model/")
onnx.save_model(onnx_model, "vit_h_encoder_external.onnx", save_as_external_data=True, all_tensors_to_one_file=True, location="vit_h_encoder.onnx", size_threshold=1024, convert_attribute=False)`


However when running below code for gnerating the embeddings i am getting issue.

`encoder = ort.InferenceSession("vit_h_encoder.onnx")
outputs = encoder.run(None,{"images":input_tensor})
embeddings = outputs[0]`

this is the issue i am getting. ===> InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from vit_h_encoder.onnx failed:Protobuf parsing failed.

Could you please help me here? Thank You!

**Comment by AndreyGermanov** [comment]
Again you try to create and load the ONNX file which is more than 2 GB, but it's not supported by ONNX Runtime. 

This is an internal problem of ONNXRuntime, that depends on Protobuf. PROTOBUF does not support more than 2GB in a single block.

Try to follow this thread to find a solution: https://github.com/pytorch/pytorch/issues/43610
