### ISSUE TITLE
SAM mask not accurate for some inputs

### ISSUE THREAD

**Issue by aganesh9** [AndreyGermanov/sam_onnx_full_export#4]
Hi Andrey,

Thank you so much for this git repo, it is very useful. I'm following your inference [example](https://github.com/AndreyGermanov/sam_onnx_full_export/blob/main/sam_onnx_inference.ipynb) to setup SAM. However, I am using vit h model instead of vit b, so would I have to change the input normalization numbers you use in your script before getting the image tensor? How are these numbers derived ?

```
mean = np.array([123.675, 116.28, 103.53])

std = np.array([[58.395, 57.12, 57.375]])
```

**Comment by AndreyGermanov** [comment]
Hello,

It's derived from original SAM code, from here: https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/sam.py#L27. It uses the same normalization numbers for all models by default.

You are free to change them to others, if it gives better results for your images.

**Comment by aganesh9** [comment]
Thanks for clarifying!

I have some images for which I am getting a bad result with the onnx model compared to the original pytorch model. When I explicitly save my input image as JPEG and pass it to the onnx model, it works perfectly fine. Are you aware of any issues with the onnx model only being able to accept jpeg input images ?

**Comment by AndreyGermanov** [comment]
> Thanks for clarifying!
> 
> I have some images for which I am getting a bad result with the onnx model compared to the original pytorch model. When I explicitly save my input image as JPEG and pass it to the onnx model, it works perfectly fine. Are you aware of any issues with the onnx model only being able to accept jpeg input images ?

Did not experience this in practice, but It's theoretically possible. When save the image to JPEG, the quality of image decreases and to hide compression artifacts, the algorithm can apply antialiasing to the image, to make smooth transitions between colors (it's not true for initial JPEG implementation, but can be applied when save in modern apps). This process is similar to Gaussian Blur filter with small radius. Such filters recommended to use as a preprocessing step in computer vision and can help.
